### ISSUE TITLE
Establish copy and paste functionality for noVNC

### ISSUE THREAD

**Issue by zachmandeville** [ii/iipod#4]
In our iipod, we offer a noVNC desktop environment that, by default, does not have the most intuitive copy and paste functionality.  There is an in-progress branch of noVNC that brings in better copy-paste support.

In this ticket, establish how copy and paste currently works in noVNC, bring in the work of the copy/paste branch, and establish how copy and paste works after bringing in that work.

Ideally, there is functionality within our NoVNC service to copy test within that remote environment and paste it in your local environment, and this functionality works across browsers.  If that is not easily possible, then let us at least establish what is currently possible and the work required to get that functionality.

**Comment by hh** [comment]
Mostly works, mostly harmless. :)
